name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          version: 22

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: push to Artifact Registry
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/zach-training-area/notely-ar-repo/notely:latest .

      - name: DB migration
        run: npm run db:migrate

      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy notely --image us-central1-docker.pkg.dev/zach-training-area/notely-ar-repo/notely:latest 
          --region us-central1 --allow-unauthenticated 
          --project zach-training-area --max-instances=4
